CREATE DATABASE bEJibun
GO
USE bEJibun
GO

CREATE TABLE[MsVendor](
	VendorID CHAR(5) PRIMARY KEY CHECK(VendorID LIKE 'VE[0-9][0-9][0-9]') NOT NULL,
	VendorName VARCHAR(255) NOT NULL,
	VendorPhone VARCHAR(20) NOT NULL,
	VendorAddress VARCHAR(255) CHECK(VendorAddress LIKE '% Street') NOT NULL,
	VendorEmail VARCHAR(255) CHECK(VendorEmail LIKE '%.com' AND VendorEmail LIKE '%@%' AND VendorEmail NOT LIKE '%@.com' AND VendorEmail NOT LIKE '@%') NOT NULL
);

CREATE TABLE[MsStaff](
	StaffID CHAR(5) PRIMARY KEY CHECK(StaffID LIKE 'ST[0-9][0-9][0-9]') NOT NULL,
	StaffName VARCHAR(255) NOT NULL,
	StaffGender VARCHAR(6) CHECK(StaffGender IN ('Male', 'Female')) NOT NULL,
	StaffPhone VARCHAR(20) NOT NULL,
	StaffSalary INT CHECK(StaffSalary > 0) NOT NULL
);

CREATE TABLE[MsItemType](
	ItemTypeID CHAR(5) PRIMARY KEY CHECK(ItemTypeID LIKE 'IP[0-9][0-9][0-9]') NOT NULL,
	ItemTypeName VARCHAR(255) CHECK(LEN(ItemTypeName)>=4)NOT NULL
);

CREATE TABLE[MsItem](
	ItemID CHAR(5) PRIMARY KEY CHECK(ItemID LIKE 'IT[0-9][0-9][0-9]') NOT NULL,
	ItemTypeID CHAR(5) FOREIGN KEY REFERENCES MsItemType(ItemTypeID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	ItemName VARCHAR(255) NOT NULL,
	ItemPrice INT CHECK(ItemPrice > 0) NOT NULL,
	ItemMinimumPurchase INT NOT NULL
);

CREATE TABLE[MsCustomer](
	CustomerID CHAR(5) PRIMARY KEY CHECK(CustomerID LIKE 'CU[0-9][0-9][0-9]') NOT NULL,
	CustomerName VARCHAR(255) NOT NULL,
	CustomerGender VARCHAR(6) CHECK(CustomerGender IN('Male', 'Female')) NOT NULL,
	CustomerPhone VARCHAR(20) NOT NULL,
	CustomerDoB DATE CHECK(CustomerDoB BETWEEN '1990-01-1' AND CAST(GETDATE() AS DATE)) NOT NULL
);

CREATE TABLE[PurchaseTransactionHeader](
	PurchaseID CHAR(5) PRIMARY KEY CHECK(PurchaseID LIKE 'PH[0-9][0-9][0-9]') NOT NULL,
	StaffID CHAR(5) FOREIGN KEY REFERENCES MsStaff(StaffID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	VendorID CHAR(5) FOREIGN KEY REFERENCES MsVendor(VendorID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	PurchaseDate DATE NOT NULL,
	ArrivalDate DATE
);

CREATE TABLE[PurchaseTransactionDetail](
	PurchaseID CHAR(5) FOREIGN KEY REFERENCES PurchaseTransactionHeader(PurchaseID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	ItemID CHAR(5) FOREIGN KEY REFERENCES MsItem(ItemID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	PurchaseQuantity INT NOT NULL,
	PRIMARY KEY(PurchaseID, ItemID)
);

CREATE TABLE[SalesTransactionHeader](
	SalesID CHAR(5) PRIMARY KEY CHECK(SalesID LIKE 'SA[0-9][0-9][0-9]') NOT NULL,
	StaffID CHAR(5) FOREIGN KEY REFERENCES MsStaff(StaffID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	CustomerID CHAR(5) FOREIGN KEY REFERENCES MsCustomer(CustomerID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	SalesDate DATE NOT NULL
);

CREATE TABLE[SalesTransactionDetail](
	SalesID CHAR(5) FOREIGN KEY REFERENCES SalesTransactionHeader(SalesID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	ItemID CHAR(5) FOREIGN KEY REFERENCES MsItem(ItemID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	SalesQuantity INT NOT NULL,
	PRIMARY KEY(SalesID, ItemID)
);